// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#include "StdDbtPlayerComponentsPlugin.h"

StdDbtPlayerComponentsPlugin::StdDbtPlayerComponentsPlugin()
{
}

StdDbtPlayerComponentsPlugin::~StdDbtPlayerComponentsPlugin()
{
}

QString StdDbtPlayerComponentsPlugin::name()
{
    return "StdDbtPlayerComponentsPlugin";
}

Q_EXPORT_PLUGIN2(StdDbtPlayerComponentsPlugin, StdDbtPlayerComponentsPlugin)
