// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#ifndef __STDDBTPLAYERCOMPONENTSPLUGIN_H__
#define __STDDBTPLAYERCOMPONENTSPLUGIN_H__

#include <QObject>
#include <qplugin.h>

#include <Pacpus/kernel/PacpusPluginInterface.h>

/// Auto-generated plugin class
class StdDbtPlayerComponentsPlugin
    : public QObject
    , public PacpusPluginInterface
{
    Q_OBJECT
    Q_INTERFACES(PacpusPluginInterface)

public:
    StdDbtPlayerComponentsPlugin();
    ~StdDbtPlayerComponentsPlugin();

protected:
    QString name();
};

#endif // __STDDBTPLAYERCOMPONENTSPLUGIN_H__
