// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#include "VelodyneComponentPlugin.h"

VelodyneComponentPlugin::VelodyneComponentPlugin()
{
}

VelodyneComponentPlugin::~VelodyneComponentPlugin()
{
}

QString VelodyneComponentPlugin::name()
{
    return "VelodyneComponentPlugin";
}

Q_EXPORT_PLUGIN2(VelodyneComponentPlugin, VelodyneComponentPlugin)
