// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#ifndef __VELODYNECOMPONENTPLUGIN_H__
#define __VELODYNECOMPONENTPLUGIN_H__

#include <QObject>
#include <qplugin.h>

#include <Pacpus/kernel/PacpusPluginInterface.h>

/// Auto-generated plugin class
class VelodyneComponentPlugin
    : public QObject
    , public PacpusPluginInterface
{
    Q_OBJECT
    Q_INTERFACES(PacpusPluginInterface)

public:
    VelodyneComponentPlugin();
    ~VelodyneComponentPlugin();

protected:
    QString name();
};

#endif // __VELODYNECOMPONENTPLUGIN_H__
