// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#ifndef __VELODYNEHDL64S2PLUGIN_H__
#define __VELODYNEHDL64S2PLUGIN_H__

#include <QObject>
#include <qplugin.h>

#include <Pacpus/kernel/PacpusPluginInterface.h>

/// Auto-generated plugin class
class VelodyneHDL64S2Plugin
    : public QObject
    , public PacpusPluginInterface
{
    Q_OBJECT
    Q_INTERFACES(PacpusPluginInterface)

public:
    VelodyneHDL64S2Plugin();
    ~VelodyneHDL64S2Plugin();

protected:
    QString name();
};

#endif // __VELODYNEHDL64S2PLUGIN_H__
