// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#include "VelodyneHDL64S2Plugin.h"

VelodyneHDL64S2Plugin::VelodyneHDL64S2Plugin()
{
}

VelodyneHDL64S2Plugin::~VelodyneHDL64S2Plugin()
{
}

QString VelodyneHDL64S2Plugin::name()
{
    return "VelodyneHDL64S2Plugin";
}

Q_EXPORT_PLUGIN2(VelodyneHDL64S2Plugin, VelodyneHDL64S2Plugin)
