// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#include "VelodynePCLViewerPlugin.h"

VelodynePCLViewerPlugin::VelodynePCLViewerPlugin()
{
}

VelodynePCLViewerPlugin::~VelodynePCLViewerPlugin()
{
}

QString VelodynePCLViewerPlugin::name()
{
    return "VelodynePCLViewerPlugin";
}

Q_EXPORT_PLUGIN2(VelodynePCLViewerPlugin, VelodynePCLViewerPlugin)
