// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#include "PacpusDispatcherPlugin.h"

PacpusDispatcherPlugin::PacpusDispatcherPlugin()
{
}

PacpusDispatcherPlugin::~PacpusDispatcherPlugin()
{
}

QString PacpusDispatcherPlugin::name()
{
    return "PacpusDispatcherPlugin";
}

Q_EXPORT_PLUGIN2(PacpusDispatcherPlugin, PacpusDispatcherPlugin)
