// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#ifndef __PACPUSDISPATCHERPLUGIN_H__
#define __PACPUSDISPATCHERPLUGIN_H__

#include <QObject>
#include <qplugin.h>

#include <Pacpus/kernel/PacpusPluginInterface.h>

/// Auto-generated plugin class
class PacpusDispatcherPlugin
    : public QObject
    , public PacpusPluginInterface
{
    Q_OBJECT
    Q_INTERFACES(PacpusPluginInterface)

public:
    PacpusDispatcherPlugin();
    ~PacpusDispatcherPlugin();

protected:
    QString name();
};

#endif // __PACPUSDISPATCHERPLUGIN_H__
