// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#include "CPTComponentPlugin.h"

CPTComponentPlugin::CPTComponentPlugin()
{
}

CPTComponentPlugin::~CPTComponentPlugin()
{
}

QString CPTComponentPlugin::name()
{
    return "CPTComponentPlugin";
}

Q_EXPORT_PLUGIN2(CPTComponentPlugin, CPTComponentPlugin)
