// Autogenerated file by PacpusPlugin.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#ifndef __CPTCOMPONENTPLUGIN_H__
#define __CPTCOMPONENTPLUGIN_H__

#include <qobject.h>
#include <qplugin.h>

#include "kernel/PacpusPluginInterface.h"

/// Auto-generated plugin class
class CPTComponentPlugin
    : public QObject
    , public PacpusPluginInterface
{
    Q_OBJECT
    Q_INTERFACES(PacpusPluginInterface)

public:
    CPTComponentPlugin();
    ~CPTComponentPlugin();

protected:
    QString name();
};

#endif // __CPTCOMPONENTPLUGIN_H__
